### ISSUE TITLE
Turkish Wrong Translates

### ISSUE THREAD

**Issue by zeynpcna2** [simplicialsoftware/nebulous-translations#10]
![Screenshot_1](https://github.com/user-attachments/assets/9e2f6ee3-2d0b-4b5b-b28c-55afdd3ecc9b)
![Screenshot_2](https://github.com/user-attachments/assets/ed2beaaf-52fc-42a3-adc8-422b2ddbe037)
![upload details](https://github.com/user-attachments/assets/6e077bef-faaf-4047-8e5b-02a5a846e114)
[Tr Translate edited .zip](https://github.com/user-attachments/files/16569863/Tr.Translate.edited.zip)

Line 1061 -1092
Line 1167
Line 1168 
Edited

**Comment by J0rgeF** [comment]
You can request this changes by following this tutorial and editing the strings as you want: 

https://youtu.be/ct_ZGtD9rZw?feature=shared

**Comment by J0rgeF** [comment]
Done.
