### ISSUE TITLE
Tradução PR BRASILEIRO 🇧🇷

### ISSUE THREAD

**Issue by Banned44nebu** [simplicialsoftware/nebulous-translations#17]
Cancelar 
Bloquear 
Reporta 
Copiar mensagem 
Copiar ID
Ver Perfil de (Jogador)
Enviar mensagem 

⚠️ Você tem certeza?
Remover Amigo: Nick 
⚠️ Você tem certeza?
ESPECTAR: Nick
🖥️SERVIDOR:
! Expulsar [0-31]
!Reiniciar 
!Bem vindo {Mensagem}
! Dificuldade [0-3} ou [1-4] para o modo campanha 
!Esconder 
!Convidados 
!Chat lento
!Pausar bate-papo
!Silenciar -{id}
! Administrador {id}
!permitir {id}

ID:23262964

![Screenshot_20240810-174659~2](https://github.com/user-attachments/assets/e83f52e2-aa52-4151-9abe-d76994733de0)
![Screenshot_20240810-174718~2](https://github.com/user-attachments/assets/94ac0bf4-9062-4134-b39e-5eaba91dcb4d)
![Screenshot_20240810-174744~2](https://github.com/user-attachments/assets/ef59082b-afcb-404b-b75e-539bb438238b)
![Screenshot_20240810-174818~2](https://github.com/user-attachments/assets/660f30c6-9c10-4da4-be7b-3c2749518013)

**Comment by CritiKangel** [comment]
The commands will not work if you translate them; they must remain in the original language.

You must suggest these changes by directly editing the file and pulling a request.
