### ISSUE TITLE
Update Strings Korean language 

### ISSUE THREAD

**Issue by Selangitt** [simplicialsoftware/nebulous-translations#215]
ID: 26624619

**Comment by Jeii20** [comment]
Please accesd GitHub through your desktop browser or mobile browser (with desktop mode enabled), go to the locations: `res/values-ko/strings.xml` and make the needed changes, then submit a Pull Request. If you already did it, please be patient, developer will come to your request as soon as possible. Thanks ^^

**Comment by Jeii20** [comment]
Please access GitHub through your desktop browser or mobile browser (with desktop mode enabled), go to the locations: `res/values-ko/strings.xml` and make the needed changes, then submit a Pull Request. If you already did it, please be patient, developer will come to your request as soon as possible. Thanks ^^

**Comment by Selangitt** [comment]
I did it already 3 days a go

**Comment by Jeii20** [comment]
> I did it already 3 days a go

Request for your tag by submitting an e-mail to: **simplicialsoftware@gmail.com**

**Comment by Selangitt** [comment]
Like: Translator tag request
Nebulous ID 26624619
Korean language, translated.
Fixed the typo, etc.
is it good?

**Comment by Jeii20** [comment]
Great move. After sent, be patient ^^

**Comment by Selangitt** [comment]
Haha, thanks!
by the way may I ask something?
How long on average will it take for me to get the translator tag?

**Comment by Jeii20** [comment]
> Haha, thanks!
> by the way may I ask something?
> How long on average will it take for me to get the translator tag?

It depends of the demand. I assure you ain't gonna be ignored

**Comment by Selangitt** [comment]
Okay thanks for replying to me! good luck with ur job Jeii!

**Comment by Jeii20** [comment]
😊
