### ISSUE TITLE
Arabic 

### ISSUE THREAD

**Issue by Samiksa1** [simplicialsoftware/nebulous-translations#36]
PLASMA HUNT
CIRCLE
![Screenshot_٢٠٢٤٠٨١٣_٠٥٥٩٠٤](https://github.com/user-attachments/assets/f696e7a5-530a-4f7a-9503-894478718788)

**Comment by CritiKangel** [comment]
You can edit the file directly (res/values-ar) and then pull a request. Don’t forget to add your ID at the end so we give you the tag.

**Comment by Samiksa1** [comment]
When will I translate it into Arabic?

في الثلاثاء، ١٣ أغسطس، ٢٠٢٤ ٨:٢٣ ص Ángel K ***@***.***> كتب:

**Comment by CritiKangel** [comment]
You can start translating it when you want. Take the file in res/values-ar and then edit it and pull request.

**Comment by Samiksa1** [comment]
Fine, thank you

في الثلاثاء، ١٣ أغسطس، ٢٠٢٤ ٨:٤٨ ص Ángel K ***@***.***> كتب:
