### ISSUE TITLE
Arabic ar Language Translation  

### ISSUE THREAD

**Issue by MaRs001V** [simplicialsoftware/nebulous-translations#382]
![Screenshot_٢٠٢٤٠٨٢٣_٠٣٢٦٣٦_Nebulousio](https://github.com/user-attachments/assets/09c46116-0746-4044-8ed0-72b843855ff9)

**Comment by MaRs001V** [comment]
Translation:
عند جعل سكنك المخصص سكن مجتمعي، سيظهر في علامة التبويب الخاصة بالإسكنات المجتمعية. سيكون بإمكان الآخرين مشاهدة وشراء سكنك المجتمعي! في كل مرة يشتري فيها شخص سكنك المجتمعي، ستحصل أنت (أو عشيرتك) على كمية صغيرة من البلازما. يجب أن تكون الإسكنات المجتمعية خالية من صور لأشخاص حقيقيين!

I wrote the word “skin” to “سكن” in the same way as it is pronounced in English, because we write it and deal with it like this.

**Comment by zeroo313** [comment]
عندما تجعل مظهرك المخصص مظهر مجتمعي، سيتم إظهاره في علامة تبويب المظهر المجتمعي. يمكن للأشخاص الآخرين رؤية وشراء مظهر مجتمعك! في كل مرة يشتري شخص ما مظهر مجتمعك، تحصل أنت (أو عشيرتك) على كمية صغيرة من البلازما. لا يمكن أن تكون جلود المجتمع صور لاشخاص حقيقيين!

**Comment by Jeii20** [comment]
check out #399 ^^

**Comment by zeroo313** [comment]
الترجمه⚝
عندما تجعل مظهرك المخصص مظهر مجتمعي سوف يتم اظهاره في علامة تبويب المظهر المجتمعي ويمكن للأشخاص الاخرون رؤية وشراء مظهر مجتمعك في كل مرة يشتري شخص ما مظهر مجتمعك تحصل أنت (أو عشيرتك) على كمية صغيرة من البلازما لا يمكن أن تكون جلود المجتمع صور لـ اشخاص حقيقيين!

**Comment by Jeii20** [comment]
> الترجمه⚝
> عندما تجعل مظهرك المخصص مظهر مجتمعي سوف يتم اظهاره في علامة تبويب المظهر المجتمعي ويمكن للأشخاص الاخرون رؤية وشراء مظهر مجتمعك في كل مرة يشتري شخص ما مظهر مجتمعك تحصل أنت (أو عشيرتك) على كمية صغيرة من البلازما لا يمكن أن تكون جلود المجتمع صور لـ اشخاص حقيقيين!

Translation has been submitted at #399, but thanks for that anyway ^^
