### ISSUE TITLE
Missing lines

### ISSUE THREAD

**Issue by MaRs001V** [simplicialsoftware/nebulous-translations#404]
![Screenshot_٢٠٢٤٠٨٢٨_١٨١٥٢١_Chrome](https://github.com/user-attachments/assets/e24a71d6-b580-4676-ae39-1bb13bcfa9aa)
![Screenshot_٢٠٢٤٠٨٢٨_١٨١١٣٨_Chrome](https://github.com/user-attachments/assets/c327be03-f53f-4d97-b1aa-2945b6d8bec5)

I noticed that here there are lines that are not placed 
1,473−1,428=45 line

**Comment by Jeii20** [comment]
This is not an issue. Sort of all language files have different line amount.
