### ISSUE TITLE
Problems with translation tags  

### ISSUE THREAD

**Issue by dbswlstjr2** [simplicialsoftware/nebulous-translations#424]
Hello, I don't know if I can post something like this here, but I think it needs to be discussed, so I'm writing this. 
This time, translation tags were added, so many users are translating to get tags, but it seems that they are also editing and uploading the correct translations. For example, they are using spacing and similar words to make it look like they have translated it.
It seems problematic to change a translation that doesn't necessarily need to be changed and get a translation tag. 

References 
![Screenshot_20240829_164007_Chrome](https://github.com/user-attachments/assets/c60f2052-ad6e-4ebb-b3e4-28c0e547752b)
![Screenshot_20240829_164003_Chrome](https://github.com/user-attachments/assets/a0dce917-2a20-4485-a536-fdc46ad36b41)

**Comment by Aybar1881** [comment]
Yeah it is happenin' so much Greg know this.
So he is now more careful when giving out tags. But not everyone like this some people doin' this thing with properly. But i am givin' you right. You're Right!
