### ISSUE TITLE
Albanian Language 

### ISSUE THREAD

**Issue by UrimShala** [simplicialsoftware/nebulous-translations#641]
Is it possible to add the game to albanian language too and how, i want to make nebulous fame in albania and kosovo too.

And in game isn’t a kosovo flag-skin too 👎

**Comment by Jeii20** [comment]
If you want to request feature in-game, please go to [**suggestions**](https://discord.com/channels/941543004026572811/941680724963123200). I ain't gonna close this issue because this is also a language request.

**Comment by UrimShala** [comment]
How can i add the albanian language? ^^

**Comment by Jeii20** [comment]
@UrimShala answering your question,
Please be patient, only the developer will do it as soon as he check your issue and you will know about it.

**Comment by UrimShala** [comment]
Thank you for your time

**Comment by Jeii20** [comment]
@UrimShala there already exists an Albanian file. It's displayed as `values-sq`. Go check out.
