### ISSUE TITLE
Bug comunidade 

### ISSUE THREAD

**Issue by Nobodykkkkkk** [simplicialsoftware/nebulous-translations#770]
Jogo simplesmente fecha aleatoriamente do nada quando abre comunidade na hora que entra no jogo.
Seria isso um bug ou real problema do jogo não se suportar?
Seria uma possível solução mudar a interface de onde fica as skins, pets, bones e etc.

**Comment by Jeii20** [comment]
Hi,
Please do not discuss this topic here. If you want to report bug, please go to the [bug reports](https://discord.com/channels/941543004026572811/941555807324082247) channel. This tab can only be used for **translation issues** or similar. Thanks ^^
