### ISSUE TITLE
for translation tag

### ISSUE THREAD

**Issue by buraksrg** [simplicialsoftware/nebulous-translations#862]
I have been actively playing the game for 9 years, I have helped people a lot in communication and at the same time I know 3 languages, Turkish and English,Uk, is it possible for me to get a translator tag that can help this game?  @Majaaaa1 

some words I corrected:
![Ekran_goruntusu_2024-10-06_223518](https://github.com/user-attachments/assets/27d57a3e-03bf-4628-a380-5996d8a370ae)
![Ekran_goruntusu_2024-10-06_214618](https://github.com/user-attachments/assets/1f099145-7eb5-4fbe-9b32-abd28b9e3e25)

**Comment by AnkaKoxu** [comment]
Unfortunately, Issues tab isn't the appropriate thread for tag requests. Only translations can be reported here.

**Comment by Jeiii20** [comment]
Hi, @buraksrg 

Please do not use the issue tracker to request for tag. You need to provide your ID on either PR description or PR comments section and please be patient if you already did so. Thank you ^^
