### ISSUE TITLE
Mistranslation Korean

### ISSUE THREAD

**Issue by Yuxi57** [simplicialsoftware/nebulous-translations#916]
![IMG_1291](https://github.com/user-attachments/assets/199461b4-2536-43d9-82ff-be74b6cdea43)

If you press the question mark button on the right side of the top, it looks like a picture, but the word 자습서 in the picture has been mistranslated
You need to fix it with the words 튜토리얼 or 도움말
That word is completely wrong

**Comment by Yuxi57** [comment]
ID 18341746

**Comment by Jeiii20** [comment]
Hi, @Yuxi57,

Please consider managing these words at `res/values-ko` and submit a pull request with them. Thanks for your report.

Good luck ^^

**Comment by Yuxi57** [comment]
> Hi, @Yuxi57,
> 
> Please consider managing these words at `res/values-ko` and submit a pull request with them. Thanks for your report.
> 
> Good luck ^^

I've reviewed the command, but there's no command that can translate that part.

**Comment by Jeiii20** [comment]
Are you sure, @Yuxi57?

![Screenshot_20241108_135623_GitHub.jpg](https://github.com/user-attachments/assets/d76855e0-78d1-4722-adf3-1211f8822fd2)

**Comment by Yuxi57** [comment]
> Are you sure, @Yuxi57?
> 
> ![Screenshot_20241108_135623_GitHub.jpg](https://private-user-images.githubusercontent.com/185197651/384456940-d76855e0-78d1-4722-adf3-1211f8822fd2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDg1MjcsIm5iZiI6MTczMTE0ODIyNywicGF0aCI6Ii8xODUxOTc2NTEvMzg0NDU2OTQwLWQ3Njg1NWUwLTc4ZDEtNDcyMi1hZGYzLTEyMTFmODgyMmZkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxMDMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmFhN2UxODg0ZGZlYmZjYjc1YjE2YjVlMjFlYzA4ZTkwZmUxZTNkZWJhOGQyYTQxZThkODEzYjM4NWUwZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oY_HdqbZRJaFyx6Z7x8tMCRsZ-l_r7iDQ8071XoXqtM)

Oh i see😅😅

**Comment by Yuxi57** [comment]
When can I get the translator title?

**Comment by Jeiii20** [comment]
@Yuxi57 

Please be patient, I cannot reply to your question. And also, it's not worth to make changes **just for the translator tag**. The tag needs to keep its value.
