### ISSUE TITLE
Mail Translation 

### ISSUE THREAD

**Issue by Maniaccc-332** [simplicialsoftware/nebulous-translations#948]
![IMG_20241122_233745](https://github.com/user-attachments/assets/314576ab-46c0-48ed-b569-9c715cff3148)
Obsequio de plasma recibido 
Name (ID): ¡Te envié un regalo de 0 plasma!

**Comment by Maniaccc-332** [comment]
Kevin_lele (11212557

**Comment by Jeiii20** [comment]
Please keep the issue open, @Maniaccc-332.
