### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by 0821283350** [simplicialsoftware/nebulous-translations#972]
Sorry, some of the text is not completely translated.And it is not available in Thai language files.See the image below for proof of translation.

![Screenshot_2024-12-07-08-13-57-371_software.simplicial.nebulous.jpg](https://github.com/user-attachments/assets/98758ea9-8626-4bc9-90a4-fb107d617e0d)

ID18478232

**Comment by Jeiii20** [comment]
Issue closed. Duplicated from #967.
